---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: #ROLE ARN
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spot-interrupt-handler
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: spot-interrupt-handler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: spot-interrupt-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: spot-interrupt-handler
  name: spot-interrupt-handler
spec:
  selector:
    matchLabels:
      app: spot-interrupt-handler
  template:
    metadata:
      labels:
        app: spot-interrupt-handler
    spec:
      serviceAccountName: spot-interrupt-handler
      nodeSelector:
        lifecycle: Ec2Spot
      containers:
        - name: spot-interrupt-handler
          image: #IMAGE
          command: ["python3", "spot-interrupt-handler.py"]
          args:
            - --rebalancing-recommendation-taint
           # - --rebalancing-recommendation-cordon
            - --elb-deregistration
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
  updateStrategy:
    type: RollingUpdate